name: nopcart_flutter
description: Flutter Edition of NopStationCart

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# {version name}+{version code}
version: 2.90.0+99

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.1 # http client
  jaguar_jwt: ^3.0.0 # jwt encoder/decoder
  shared_preferences: ^2.0.5
  carousel_slider: ^4.0.0
  cached_network_image: ^3.0.0
  scoped_model: ^2.0.0-nullsafety.0
  firebase_messaging: ^14.1.0
  firebase_core: ^2.2.0
  firebase_crashlytics: ^3.0.6
  flutter_local_notifications: ^12.0.3 # TODO ios implementation
  file_picker: ^4.6.1
  flutter_barcode_scanner: ^2.0.0
  url_launcher: ^6.0.7
  permission_handler: ^10.2.0
  intl: ^0.17.0 # datetime converter
  flutter_typeahead: ^4.1.1 # search autosuggestion
  badges: ^2.0.1
  flutter_rating_bar: ^4.0.0
  mime: ^1.0.0 # to detect mimetype from file path
  flutter_inappwebview: ^5.7.2+3
  open_file_safe: ^3.2.3
  flutter_math_fork: ^0.5.0

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  collection: ^1.16.0
  popup_banner: ^1.0.0
  flutter_countdown_timer: ^4.1.0
  sprintf: ^7.0.0
  share_plus: ^4.5.3
  flutter_svg: ^0.23.0+1
  flutter_slidable: ^2.0.0
  social_login_buttons: ^1.0.7
  flutter_facebook_auth: ^4.4.1+1
  palette_generator: ^0.3.3+2
  google_maps_flutter: ^2.2.1
  html: ^0.15.1
  flutter_widget_from_html_core: ^0.9.0+1
  sign_in_with_apple: ^4.2.0
  google_sign_in: ^5.4.2
  flutter_html: ^2.2.1
  pointer_interceptor: ^0.9.3+3
  uuid: ^3.0.7
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
   - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: KhandBold
      fonts:
      - asset: fonts/khand_bold.ttf

    - family: LatoBold
      fonts:
          - asset: fonts/lato_bold.ttf

    - family: LatoRegular
      fonts:
          - asset: fonts/lato_regular.ttf

    - family: Monstserrat
      fonts:
          - asset: fonts/montserrat_regular.ttf

    - family:  NopCart
      fonts:
          - asset: fonts/NopCart.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
