// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdmRLeS-wj7gp5xBJBF_j6LxfLxjD6z0A',
    appId: '1:49771441940:web:22a5f4ba183ea36bbb9c01',
    messagingSenderId: '49771441940',
    projectId: 'storkph-297500',
    authDomain: 'storkph-297500.firebaseapp.com',
    storageBucket: 'storkph-297500.appspot.com',
    measurementId: 'G-VYBYRJY7FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYPEgsdjczkKvVhnokdPmM1ibSSGEDDCc',
    appId: '1:49771441940:android:ea2dc5924abcec50bb9c01',
    messagingSenderId: '49771441940',
    projectId: 'storkph-297500',
    storageBucket: 'storkph-297500.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDomCvC_I2mMrTUBH9aZiHf78A-JdSaMGg',
    appId: '1:49771441940:ios:1d1559461feb1d24bb9c01',
    messagingSenderId: '49771441940',
    projectId: 'storkph-297500',
    storageBucket: 'storkph-297500.appspot.com',
    androidClientId: '49771441940-da70gor1pnthavbjjfu9pf8bdvkucfp8.apps.googleusercontent.com',
    iosClientId: '49771441940-drqkjov162hnia1pd8283nckob4lb2in.apps.googleusercontent.com',
    iosBundleId: 'ph.stork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDomCvC_I2mMrTUBH9aZiHf78A-JdSaMGg',
    appId: '1:49771441940:ios:0ac0ea8da0fc24bdbb9c01',
    messagingSenderId: '49771441940',
    projectId: 'storkph-297500',
    storageBucket: 'storkph-297500.appspot.com',
    androidClientId: '49771441940-da70gor1pnthavbjjfu9pf8bdvkucfp8.apps.googleusercontent.com',
    iosClientId: '49771441940-tqsce5ite698bviq27urpn0pnf205upk.apps.googleusercontent.com',
    iosBundleId: 'stork.nopstation',
  );
}
